export const products = [
  {
    id: 1,
    name: "ধান বীজ",
    description: "উচ্চ ফলনশীল ধান বীজ, যা চাষের জন্য উপযোগী।",
    price: "২০০ টাকা",
    availability: "প্রাপ্যতা: পর্যাপ্ত পরিমাণে আছে",
    image_url: "/products/rice.jpg",
  },
  {
    id: 2,
    name: "ইউরিয়া সার",
    description: "গাছের বৃদ্ধি ও ফলন বৃদ্ধির জন্য ইউরিয়া সার।",
    price: "৮০০ টাকা",
    availability: "প্রাপ্যতা: দ্রুত কিনতে উপলব্ধ",
    image_url: "/products/uria.jpg",
  },
  {
    id: 3,
    name: "কীটনাশক",
    description: "ফসলের ক্ষতিকারক পোকামাকড় দমনের জন্য কার্যকরী কীটনাশক।",
    price: "৫০০ টাকা",
    availability: "প্রাপ্যতা: শীঘ্রই আসছে",
    image_url: "/products/kitnashok.jpg",
  },
  {
    id: 4,
    name: "সেচ পাম্প",
    description: "ফসলের জমিতে পানি সেচের জন্য শক্তিশালী সেচ পাম্প।",
    price: "১৫০০ টাকা",
    availability: "প্রাপ্যতা: পর্যাপ্ত পরিমাণে আছে",
    image_url: "/products/pump.jpg",
  },
  {
    id: 5,
    name: "কম্পোস্ট সার",
    description: "জৈব উপাদানে তৈরি কম্পোস্ট সার, যা মাটির উর্বরতা বৃদ্ধি করে।",
    price: "৩০০ টাকা",
    availability: "প্রাপ্যতা: দ্রুত কিনতে উপলব্ধ",
    image_url: "/products/compost.jpg",
  },
  {
    id: 6,
    name: "কৃষি যন্ত্রপাতি",
    description: "জমি চাষের জন্য প্রয়োজনীয় কৃষি যন্ত্রপাতি।",
    price: "২৫০০ টাকা",
    availability: "প্রাপ্যতা: পর্যাপ্ত পরিমাণে আছে",
    image_url: "/products/machines.jpg",
  },
];
